spring.application.name=portfolio-backend

# Disable DB completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Server
server.port=${PORT:8080}
server.servlet.context-path=/